extends Node
## Main scene placeholder generated by game-builder. Replace it with the first playable
## described in the approved spec — it exists so the project boots and `gb verify` has a scene to run.


func _ready() -> void:
	print("game-builder: main scene ready")
