extends GutTest
## Example unit test generated by game-builder. GUT runs every tests/**/test_*.gd file:
##   node tools/gb/gb.js test
## Test logic that can be wrong silently (damage, inventory, state machines, save data) here;
## movement feel and fun go to scenarios and the human playtest gate instead.


func test_events_autoload_exists() -> void:
	assert_not_null(get_node_or_null("/root/Events"), "Events autoload is registered")


func test_harness_is_inert_in_normal_runs() -> void:
	var harness := get_node_or_null("/root/GbHarness")
	assert_not_null(harness, "GbHarness autoload is registered")
	assert_false(harness.active, "harness does nothing without --gb-* arguments")
