'use strict';

// gb credits — builds CREDITS.md from .ai/assets/REGISTER.md and blocks licences that cannot ship.
// Register columns: | Path | Source | Author | Licence | Attribution needed | Added |

const fs = require('fs');
const path = require('path');

// Licences that must not ship in a released game without extra permission.
const BLOCK = [
  [/\bNC\b|non-?commercial|niekomerc/i, 'non-commercial licence'],
  [/\bND\b|no-?deriv/i, 'no-derivatives licence (edits and game integration may violate it)'],
  [/brak|unknown|none|\?|nieznan|royalty.?free$/i, 'no identifiable licence'],
  [/all rights reserved|©|\(c\)|ripped|from the game/i, 'proprietary material'],
  [/polyform|ready ?player ?me|adobe research/i, 'licence restricted to its own platform/research'],
];
const NEEDS_CREDIT = /CC[- ]?BY(?!.*NC)|attribution|OFL|MIT|BSD|Apache|zlib/i;

function parseRegister(text) {
  const rows = [];
  for (const line of text.split(/\r?\n/)) {
    if (!/^\|/.test(line) || /^\|\s*-+/.test(line) || /\|\s*Path\s*\|/i.test(line)) continue;
    const c = line.split('|').slice(1, -1).map((s) => s.trim());
    if (c.length < 4 || !c[0]) continue;
    rows.push({ path: c[0].replace(/`/g, ''), source: c[1] || '', author: c[2] || '', licence: c[3] || '', attribution: c[4] || '', added: c[5] || '' });
  }
  return rows;
}

function check(rows, projectDir) {
  const problems = [];
  for (const r of rows) {
    for (const [re, why] of BLOCK) if (re.test(r.licence)) { problems.push(`${r.path}: ${why} ("${r.licence}")`); break; }
    if (/CC[- ]?BY/i.test(r.licence) && !r.attribution && !r.author) problems.push(`${r.path}: CC-BY without author/attribution text`);
    if (projectDir && !fs.existsSync(path.join(projectDir, r.path.replace(/^res:\/\//, '')))) problems.push(`${r.path}: listed in the register but not found`);
  }
  return problems;
}

function render(rows, title) {
  const groups = new Map();
  for (const r of rows) {
    const key = `${r.author || 'Unknown author'}|${r.licence}|${r.source}`;
    if (!groups.has(key)) groups.set(key, { ...r, files: [] });
    groups.get(key).files.push(r.path);
  }
  let md = `# Credits — ${title}\n\nThird-party assets used in this game (generated by \`gb credits\` from \`.ai/assets/REGISTER.md\`).\n\n`;
  for (const g of [...groups.values()].sort((a, b) => a.author.localeCompare(b.author))) {
    md += `- **${g.author || 'Unknown author'}** — ${g.licence}${g.source ? ` — ${g.source}` : ''}\n`;
    if (g.attribution && !/^(no|nie|-|—)$/i.test(g.attribution)) md += `  ${g.attribution}\n`;
    md += `  Files: ${g.files.slice(0, 6).join(', ')}${g.files.length > 6 ? ` (+${g.files.length - 6} more)` : ''}\n`;
  }
  const needCredit = rows.filter((r) => NEEDS_CREDIT.test(r.licence)).length;
  md += `\n${rows.length} registered asset(s); ${needCredit} under licences that require keeping the notice or attribution.\n`;
  return md;
}

module.exports = { parseRegister, check, render };
