'use strict';

/**
 * gb scaffold — generate a new game-builder Godot project (game-bootstrap Case B), or add the
 * missing methodology pieces to an existing one (Case C, --adopt).
 *
 * IDEMPOTENT by construction: an existing file is never overwritten — it is reported as KEPT.
 * That is what makes Case C safe (adopting a running project must not touch its code) and what
 * makes a re-run after a partial failure harmless.
 *
 * Runs from the PLUGIN copy only (it needs ../../templates). The copy of tools/gb placed into the
 * game repo does not carry this file.
 */

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const PLUGIN = path.resolve(__dirname, '..', '..');
const TPL = path.join(PLUGIN, 'templates');

const RENDERERS = {
  forward_plus: 'Forward Plus',
  mobile: 'Mobile',
  gl_compatibility: 'GL Compatibility',
};

function pluginVersion() {
  try {
    return fs.readFileSync(path.join(PLUGIN, 'VERSION'), 'utf8').trim();
  } catch {
    return '0.0.0';
  }
}

function projectGodot(o) {
  const pixel = o.pixelArt;
  const lines = [
    '; Engine configuration file. Generated by game-builder scaffold; edit through the Godot editor.',
    '',
    'config_version=5',
    '',
    '[application]',
    '',
    `config/name="${o.name.replace(/"/g, '\\"')}"`,
    'run/main_scene="res://scenes/main.tscn"',
    `config/features=PackedStringArray("${o.engine}", "${RENDERERS[o.renderer]}")`,
    '',
    '[autoload]',
    '',
    'Events="*res://autoload/events.gd"',
    '',
    '[display]',
    '',
    `window/size/viewport_width=${o.width}`,
    `window/size/viewport_height=${o.height}`,
    ...(pixel && o.width * 4 <= 1920 ? [`window/size/window_width_override=${o.width * 4}`, `window/size/window_height_override=${o.height * 4}`] : []),
    `window/stretch/mode="${pixel ? 'viewport' : 'canvas_items'}"`,
    `window/stretch/aspect="${pixel ? 'keep' : 'expand'}"`,
    '',
    '[rendering]',
    '',
    `renderer/rendering_method="${o.renderer}"`,
    `renderer/rendering_method.mobile="${o.renderer === 'forward_plus' ? 'mobile' : o.renderer}"`,
  ];
  if (pixel) lines.push('textures/canvas_textures/default_texture_filter=0', '2d/snap/snap_2d_transforms_to_pixel=true');
  return lines.join('\n') + '\n';
}

function mainScene(o) {
  const head = `[gd_scene format=3]\n\n[ext_resource type="Script" path="res://scripts/main.gd" id="1_main"]\n\n`;
  const label = o.name.replace(/"/g, '\\"');
  if (o.dim === '3d') {
    return head +
      `[node name="Main" type="Node3D"]\nscript = ExtResource("1_main")\n\n` +
      `[node name="Camera3D" type="Camera3D" parent="."]\ntransform = Transform3D(1, 0, 0, 0, 0.939693, 0.34202, 0, -0.34202, 0.939693, 0, 3, 6)\n\n` +
      `[node name="Sun" type="DirectionalLight3D" parent="."]\ntransform = Transform3D(1, 0, 0, 0, 0.707107, 0.707107, 0, -0.707107, 0.707107, 0, 5, 0)\n\n` +
      `[node name="Floor" type="CSGBox3D" parent="."]\ntransform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.5, 0)\nuse_collision = true\nsize = Vector3(20, 1, 20)\n\n` +
      `[node name="Label" type="Label" parent="."]\noffset_left = 16.0\noffset_top = 16.0\ntext = "${label} — game-builder"\n`;
  }
  return head +
    `[node name="Main" type="Node2D"]\nscript = ExtResource("1_main")\n\n` +
    `[node name="Camera2D" type="Camera2D" parent="."]\nanchor_mode = 0\n\n` +
    `[node name="Label" type="Label" parent="."]\noffset_left = 16.0\noffset_top = 16.0\ntext = "${label} — game-builder"\n`;
}

const GITIGNORE = `# Godot 4.1+ (see Godot docs: Version control systems)
.godot/
*.translation

# Exported builds
build/

# game-builder local state
.ai/verify/
.claude/worktrees/
.claude/status/
.claude/settings.local.json
`;

function gitattributes(lfs) {
  let s = '# Normalize line endings (Godot files use LF)\n* text=auto eol=lf\n\n# Binary assets\n';
  const bin = ['png', 'jpg', 'jpeg', 'webp', 'svgz', 'wav', 'ogg', 'mp3', 'glb', 'fbx', 'blend', 'obj', 'ttf', 'otf', 'exr', 'hdr', 'psd', 'aseprite', 'zip'];
  for (const e of bin) s += lfs ? `*.${e} filter=lfs diff=lfs merge=lfs -text\n` : `*.${e} binary\n`;
  return s;
}

const EDITORCONFIG = `root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true

[*.gd]
indent_style = tab

[*.{js,json,md,yml,yaml}]
indent_style = space
indent_size = 2
`;

const IGNORE_ERRORS = `# One regular expression per line: log lines matching them are NOT counted as errors by gb.
# Every entry needs a comment above it saying WHY it is safe to ignore. Silencing a real error to
# make verify pass is forbidden (AGENTS.md hard safety rules).
`;

function readme(o) {
  return `# ${o.name}

Gra w Godot ${o.engine} (${o.dim.toUpperCase()}), zbudowana metodą game-builder.

- Uruchom: otwórz folder w Godocie ${o.engine} i naciśnij F5.
- Sprawdź, czy wszystko działa: \`node tools/gb/gb.js verify\`
- Koncepcja: \`.ai/brief.md\` · specyfikacje: \`.ai/specs/\` · postęp: \`STATUS.md\`
`;
}

function adr001(o) {
  return `# ADR-001: Engine and project setup

Date: ${new Date().toISOString().slice(0, 10)}
Status: accepted

## Decision
- Engine: Godot ${o.engine}, GDScript with static typing
- Dimension: ${o.dim.toUpperCase()}
- Renderer: ${RENDERERS[o.renderer]} (\`${o.renderer}\`)
- Base resolution: ${o.width}×${o.height}${o.pixelArt ? ', pixel-art settings (viewport stretch, nearest filter, 2D pixel snap)' : ''}
- Test framework: ${o.tests}
- Git LFS for binary assets: ${o.lfs ? 'yes' : 'no'}

## Context
Chosen by the human in game-bootstrap from decision cards; see the Decisions Ledger in \`.ai/brief.md\`.

## Consequences
${o.renderer === 'gl_compatibility' ? '- Web export possible (Godot 4 web export requires the Compatibility renderer); fewer advanced 3D effects.\n' : ''}${o.renderer === 'forward_plus' ? '- Best desktop 3D quality; no web export without switching to Compatibility.\n' : ''}${o.lfs ? '- Binary assets go through Git LFS: every clone needs `git lfs install`; hosting quota applies.\n' : '- Binary assets are committed directly: keep the repository small, revisit LFS if assets grow past a few hundred MB.\n'}`;
}

function fill(tpl, o) {
  return tpl
    .replace(/\{\{NAME\}\}/g, o.name)
    .replace(/\{\{VERSION\}\}/g, pluginVersion())
    .replace(/\{\{ENGINE\}\}/g, o.engine)
    .replace(/\{\{DIM\}\}/g, o.dim.toUpperCase())
    .replace(/\{\{RENDERER\}\}/g, `${RENDERERS[o.renderer]} (\`${o.renderer}\`)`)
    .replace(/\{\{WIDTH\}\}/g, String(o.width))
    .replace(/\{\{HEIGHT\}\}/g, String(o.height))
    .replace(/\{\{PIXEL_NOTE\}\}/g, o.pixelArt ? ' · pixel art (viewport stretch, nearest filter, pixel snap)' : '')
    .replace(/\{\{TESTS\}\}/g, o.tests === 'none' ? 'none yet (decided later; `gb test` reports SKIP)' : `${o.tests} (installed into addons/ — until then \`gb test\` reports SKIP)`);
}

function plan(o) {
  const files = [];
  const add = (rel, content, mode) => files.push({ rel, content, mode });
  const copy = (rel, src) => files.push({ rel, src });

  add('project.godot', projectGodot(o));
  add('scenes/main.tscn', mainScene(o));
  copy('scripts/main.gd', path.join(TPL, 'project', 'scripts', 'main.gd'));
  copy('autoload/events.gd', path.join(TPL, 'project', 'autoload', 'events.gd'));
  add('assets/.gitkeep', '');
  add('data/.gitkeep', '');
  add('tests/README.md', '# Tests\n\nRun with `node tools/gb/gb.js test`. Test files: `test_*.gd`. See `.ai/checklists/testing.md`.\n');
  add('.gitignore', GITIGNORE);
  add('.gitattributes', gitattributes(o.lfs));
  add('.editorconfig', EDITORCONFIG);

  for (const f of ['gb.js', 'check_all.gd', 'setup_input.gd']) copy(`tools/gb/${f}`, path.join(__dirname, f));
  add('tools/gb/.gdignore', '');
  add('tools/gb/ignore-errors.txt', IGNORE_ERRORS);

  add('AGENTS.md', fill(fs.readFileSync(path.join(TPL, 'repo', 'AGENTS.md.tmpl'), 'utf8'), o));
  add('CLAUDE.md', '@AGENTS.md\n');
  add('README.md', readme(o));
  add('STATUS.md', `# Status — ${o.name}\n\nPostęp gry wg specyfikacji (aktualizowany na każdej bramce fazy).\n\n| Spec | Faza | Stan | Grywalne? | Werdykt gracza |\n|---|---|---|---|---|\n`);

  const aiFiles = JSON.parse(fs.readFileSync(path.join(TPL, 'ai', 'files.json'), 'utf8'));
  for (const [rel, content] of Object.entries(aiFiles)) if (!rel.startsWith('_')) add(`.ai/${rel}`, content);
  for (const c of fs.readdirSync(path.join(TPL, 'ai', 'checklists'))) copy(`.ai/checklists/${c}`, path.join(TPL, 'ai', 'checklists', c));
  copy('.ai/skills/spec-writing/SKILL.md', path.join(TPL, 'ai', 'skills', 'spec-writing', 'SKILL.md'));
  add('.ai/adr/ADR-001-engine-and-setup.md', adr001(o));

  copy('.claude/settings.json', path.join(TPL, 'claude', 'settings.json'));
  copy('.claude/hooks/session-start.sh', path.join(TPL, 'claude', 'hooks', 'session-start.sh'));
  copy('.claude/hooks/guard-protected-paths.sh', path.join(TPL, 'claude', 'hooks', 'guard-protected-paths.sh'));
  return files;
}

/**
 * In adopt mode the game's own files are never generated — only the methodology layer + tools.
 * Even then nothing existing is overwritten (the general rule), but skipping these keeps the
 * report honest: an adopted project does not get a placeholder main scene "KEPT" next to its own.
 */
const GAME_FILES = new Set(['project.godot', 'scenes/main.tscn', 'scripts/main.gd', 'autoload/events.gd', 'assets/.gitkeep', 'data/.gitkeep']);

function scaffold(o, { runGodot = null, dryRun = false } = {}) {
  const report = [];
  for (const f of plan(o)) {
    if (o.adopt && GAME_FILES.has(f.rel)) continue;
    const dst = path.join(o.dir, f.rel);
    if (fs.existsSync(dst)) { report.push(`KEPT    ${f.rel}`); continue; }
    report.push(`CREATED ${f.rel}`);
    if (dryRun) continue;
    fs.mkdirSync(path.dirname(dst), { recursive: true });
    if (f.src) fs.copyFileSync(f.src, dst);
    else fs.writeFileSync(dst, f.content);
  }
  if (!dryRun && runGodot) {
    const r = runGodot(['--headless', '--path', o.dir, '--script', path.join(o.dir, 'tools', 'gb', 'setup_input.gd')]);
    const m = /GB_INPUT_DONE added=(\d+) err=(\d+)/.exec(r);
    report.push(m ? `INPUT   ${m[1]} default action(s) added via Godot (existing actions untouched)` : 'FAIL    input actions: setup_input.gd did not report — run it manually');
  }
  return report;
}

function parseScaffoldArgs(argv) {
  const o = { dir: process.cwd(), name: null, dim: '2d', renderer: null, pixelArt: false, width: null, height: null, tests: 'gut', lfs: false, engine: null, adopt: false, dryRun: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const v = () => argv[++i];
    if (a === '--dir') o.dir = path.resolve(v());
    else if (a === '--name') o.name = v();
    else if (a === '--dim') o.dim = v().toLowerCase();
    else if (a === '--renderer') o.renderer = v();
    else if (a === '--pixel-art') o.pixelArt = true;
    else if (a === '--width') o.width = Number(v());
    else if (a === '--height') o.height = Number(v());
    else if (a === '--tests') o.tests = v();
    else if (a === '--lfs') o.lfs = true;
    else if (a === '--engine') o.engine = v();
    else if (a === '--adopt') o.adopt = true;
    else if (a === '--dry-run') o.dryRun = true;
    else throw new Error(`scaffold: unknown option ${a}`);
  }
  if (!['2d', '3d'].includes(o.dim)) throw new Error('scaffold: --dim must be 2d or 3d');
  o.renderer = o.renderer || (o.dim === '3d' ? 'forward_plus' : 'gl_compatibility');
  if (!RENDERERS[o.renderer]) throw new Error(`scaffold: --renderer must be one of ${Object.keys(RENDERERS).join(', ')}`);
  if (!['gut', 'gdunit4', 'none'].includes(o.tests)) throw new Error('scaffold: --tests must be gut, gdunit4 or none');
  o.width = o.width || (o.pixelArt ? 320 : 1280);
  o.height = o.height || (o.pixelArt ? 180 : 720);
  o.name = o.name || path.basename(o.dir);
  return o;
}

module.exports = { scaffold, parseScaffoldArgs, projectGodot, mainScene, plan, RENDERERS };
