'use strict';

/**
 * gb scaffold — generate a new game-builder Godot project (game-bootstrap Case B), or add the
 * missing methodology pieces to an existing one (Case C, --adopt).
 *
 * IDEMPOTENT by construction: an existing file is never overwritten — it is reported as KEPT.
 * That is what makes Case C safe (adopting a running project must not touch its code) and what
 * makes a re-run after a partial failure harmless.
 *
 * Runs from the PLUGIN copy only (it needs ../../templates). The copy of tools/gb placed into the
 * game repo does not carry this file.
 */

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const PLUGIN = path.resolve(__dirname, '..', '..');
const TPL = path.join(PLUGIN, 'templates');

const RENDERERS = {
  forward_plus: 'Forward Plus',
  mobile: 'Mobile',
  gl_compatibility: 'GL Compatibility',
};

function pluginVersion() {
  try {
    return fs.readFileSync(path.join(PLUGIN, 'VERSION'), 'utf8').trim();
  } catch {
    return '0.0.0';
  }
}

function projectGodot(o) {
  const pixel = o.pixelArt;
  const lines = [
    '; Engine configuration file. Generated by game-builder scaffold; edit through the Godot editor.',
    '',
    'config_version=5',
    '',
    '[application]',
    '',
    `config/name="${o.name.replace(/"/g, '\\"')}"`,
    `run/main_scene="${o.templateInfo ? o.templateInfo.main_scene : 'res://scenes/main.tscn'}"`,
    `config/features=PackedStringArray("${o.engine}", "${RENDERERS[o.renderer]}")`,
    '',
    '[autoload]',
    '',
    'Events="*res://autoload/events.gd"',
    'GbHarness="*res://addons/gb_harness/harness.gd"',
    '',
    ...(o.tests === 'gut' ? ['[editor_plugins]', '', 'enabled=PackedStringArray("res://addons/gut/plugin.cfg")', ''] : []),
    '[display]',
    '',
    `window/size/viewport_width=${o.width}`,
    `window/size/viewport_height=${o.height}`,
    ...(o.templateInfo && o.templateInfo.window
      ? [`window/size/window_width_override=${o.templateInfo.window[0]}`, `window/size/window_height_override=${o.templateInfo.window[1]}`]
      : pixel && o.width * 4 <= 1920 ? [`window/size/window_width_override=${o.width * 4}`, `window/size/window_height_override=${o.height * 4}`] : []),
    `window/stretch/mode="${pixel ? 'viewport' : 'canvas_items'}"`,
    `window/stretch/aspect="${pixel ? 'keep' : 'expand'}"`,
    // integer scaling keeps pixels square and crisp (Godot 4.7 docs: display/window/stretch/scale_mode)
    ...(pixel ? ['window/stretch/scale_mode="integer"'] : []),
    '',
    '[rendering]',
    '',
    `renderer/rendering_method="${o.renderer}"`,
    `renderer/rendering_method.mobile="${o.renderer === 'forward_plus' ? 'mobile' : o.renderer}"`,
  ];
  if (pixel) lines.push('textures/canvas_textures/default_texture_filter=0', '2d/snap/snap_2d_transforms_to_pixel=true');
  return lines.join('\n') + '\n';
}

function mainScene(o) {
  const head = `[gd_scene format=3]\n\n[ext_resource type="Script" path="res://scripts/main.gd" id="1_main"]\n\n`;
  const label = o.name.replace(/"/g, '\\"');
  if (o.dim === '3d') {
    return head +
      `[node name="Main" type="Node3D"]\nscript = ExtResource("1_main")\n\n` +
      `[node name="Camera3D" type="Camera3D" parent="."]\ntransform = Transform3D(1, 0, 0, 0, 0.939693, 0.34202, 0, -0.34202, 0.939693, 0, 3, 6)\n\n` +
      `[node name="Sun" type="DirectionalLight3D" parent="."]\ntransform = Transform3D(1, 0, 0, 0, 0.707107, 0.707107, 0, -0.707107, 0.707107, 0, 5, 0)\n\n` +
      `[node name="Floor" type="CSGBox3D" parent="."]\ntransform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.5, 0)\nuse_collision = true\nsize = Vector3(20, 1, 20)\n\n` +
      `[node name="Label" type="Label" parent="."]\noffset_left = 16.0\noffset_top = 16.0\ntext = "${label} — game-builder"\n`;
  }
  return head +
    `[node name="Main" type="Node2D"]\nscript = ExtResource("1_main")\n\n` +
    `[node name="Camera2D" type="Camera2D" parent="."]\nanchor_mode = 0\n\n` +
    `[node name="Label" type="Label" parent="."]\noffset_left = 16.0\noffset_top = 16.0\ntext = "${label} — game-builder"\n`;
}

const GITIGNORE = `# Godot 4.1+ (see Godot docs: Version control systems)
.godot/
*.translation

# Exported builds
build/

# game-builder local state
.ai/verify/
.claude/worktrees/
.claude/status/
.claude/settings.local.json

# Windows: "2>nul" run inside Git Bash creates a real file named nul, which git cannot index
nul
`;

function gitattributes(lfs) {
  let s = '# Normalize line endings (Godot files use LF)\n* text=auto eol=lf\n\n# Binary assets\n';
  const bin = ['png', 'jpg', 'jpeg', 'webp', 'svgz', 'wav', 'ogg', 'mp3', 'glb', 'fbx', 'blend', 'obj', 'ttf', 'otf', 'exr', 'hdr', 'psd', 'aseprite', 'zip'];
  for (const e of bin) s += lfs ? `*.${e} filter=lfs diff=lfs merge=lfs -text\n` : `*.${e} binary\n`;
  return s;
}

const EDITORCONFIG = `root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true

[*.gd]
indent_style = tab

[*.{js,json,md,yml,yaml}]
indent_style = space
indent_size = 2
`;

const IGNORE_ERRORS = `# One regular expression per line: log lines matching them are NOT counted as errors by gb.
# Every entry needs a comment above it saying WHY it is safe to ignore. Silencing a real error to
# make verify pass is forbidden (AGENTS.md hard safety rules).
`;

const TESTS_README = `# Tests

| Folder | What | Run |
|---|---|---|
| \`unit/\` (any \`test_*.gd\`) | GUT unit tests for logic | \`node tools/gb/gb.js test\` |
| \`scenarios/\` | bot-player scenarios (extend \`GbScenario\`) | \`node tools/gb/gb.js scenario\` |
| \`replays/\` | recordings of real play (\`gb record <name>\`) — regression tests | \`node tools/gb/gb.js replay\` |
| \`baselines/\` | accepted screenshots (\`gb shot --accept\`) | \`node tools/gb/gb.js shot --compare\` |

\`node tools/gb/gb.js verify\` runs unit tests, scenarios and replays. Put the nodes that matter
(player, enemies, score holder) in the group \`gb_track\` so a replay also compares their final
position and health/score/state.
`;

const PERF_BUDGET = JSON.stringify({
  _comment: 'gb perf fails when a measured value exceeds its budget. frame_ms and draw_calls are only checked in a window run.',
  frame_ms_p95: 16.7,
  process_ms_p95: 8,
  physics_ms_p95: 4,
  draw_calls_max: 2000,
  nodes_max: 20000,
  static_memory_mb_max: 1024,
}, null, 2) + '\n';

function exportPresets() {
  const preset = (idx, name, out) => `[preset.${idx}]

name="${name}"
platform="${name}"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter="tools/*, tests/*, addons/gut/*"
export_path="${out}"
script_export_mode=2
`;
  return `${preset(0, 'Windows Desktop', 'build/windows/game.exe')}
[preset.0.options]

binary_format/embed_pck=true

${preset(1, 'Web', 'build/web/index.html')}
[preset.1.options]

variant/thread_support=false
`;
}

function readme(o) {
  return `# ${o.name}

Gra w Godot ${o.engine} (${o.dim.toUpperCase()}), zbudowana metodą game-builder.

- Uruchom: otwórz folder w Godocie ${o.engine} i naciśnij F5.
- Sprawdź, czy wszystko działa: \`node tools/gb/gb.js verify\`
- Koncepcja: \`.ai/brief.md\` · specyfikacje: \`.ai/specs/\` · postęp: \`STATUS.md\`
`;
}

/** 2D/3D cannot be read from project.godot; an adopted project without --dim says so instead of guessing. */
function dimLabel(o) {
  return o.adopt && !o.dimGiven ? '2D or 3D — not detected, fill in' : o.dim.toUpperCase();
}

function adr001(o) {
  return `# ADR-001: Engine and project setup

Date: ${new Date().toISOString().slice(0, 10)}
Status: accepted

## Decision
- Engine: Godot ${o.engine}, GDScript with static typing
- Dimension: ${dimLabel(o)}
- Renderer: ${RENDERERS[o.renderer]} (\`${o.renderer}\`)
- Base resolution: ${o.width}×${o.height}${o.pixelArt ? ', pixel-art settings (viewport stretch, nearest filter, 2D pixel snap)' : ''}
- Test framework: ${o.tests}
- Git LFS for binary assets: ${o.lfs ? 'yes' : 'no'}

## Context
${o.adopt ? 'Read from the existing project.godot during adoption (game-bootstrap Case C; Godot defaults where a key is absent). Correct anything the project does differently.' : 'Chosen by the human in game-bootstrap from decision cards; see the Decisions Ledger in `.ai/brief.md`.'}

## Consequences
${o.renderer === 'gl_compatibility' ? '- Web export possible (Godot 4 web export requires the Compatibility renderer); fewer advanced 3D effects.\n' : ''}${o.renderer === 'forward_plus' ? '- Best desktop 3D quality; no web export without switching to Compatibility.\n' : ''}${o.lfs ? '- Binary assets go through Git LFS: every clone needs `git lfs install`; hosting quota applies.\n' : '- Binary assets are committed directly: keep the repository small, revisit LFS if assets grow past a few hundred MB.\n'}`;
}

function fill(tpl, o) {
  return tpl
    .replace(/\{\{NAME\}\}/g, o.name)
    .replace(/\{\{VERSION\}\}/g, pluginVersion())
    .replace(/\{\{ENGINE\}\}/g, o.engine)
    .replace(/\{\{DIM\}\}/g, dimLabel(o))
    .replace(/\{\{RENDERER\}\}/g, `${RENDERERS[o.renderer]} (\`${o.renderer}\`)`)
    .replace(/\{\{WIDTH\}\}/g, String(o.width))
    .replace(/\{\{HEIGHT\}\}/g, String(o.height))
    .replace(/\{\{PIXEL_NOTE\}\}/g, o.pixelArt ? ' · pixel art (viewport stretch, nearest filter, pixel snap)' : '')
    .replace(/\{\{TESTS\}\}/g, o.tests === 'none' ? 'none yet (decided later; `gb test` reports SKIP)' : `${o.tests} (installed into addons/ — until then \`gb test\` reports SKIP)`);
}

function plan(o) {
  const files = [];
  const add = (rel, content, mode) => files.push({ rel, content, mode });
  const copy = (rel, src) => files.push({ rel, src });
  const copyTree = (relDir, srcDir) => {
    for (const e of fs.readdirSync(srcDir, { withFileTypes: true })) {
      if (e.isDirectory()) copyTree(`${relDir}/${e.name}`, path.join(srcDir, e.name));
      else copy(`${relDir}/${e.name}`, path.join(srcDir, e.name));
    }
  };

  add('project.godot', projectGodot(o));
  if (o.templateInfo) {
    // A starter game replaces the placeholder main scene; its own files (scenes, scripts, data,
    // tests, its implemented spec) are copied as-is.
    const tdir = path.join(TPL, 'games', o.template);
    for (const e of fs.readdirSync(tdir, { withFileTypes: true })) {
      if (e.name === 'template.json') continue;
      if (e.isDirectory()) copyTree(e.name, path.join(tdir, e.name));
      else copy(e.name, path.join(tdir, e.name));
    }
  } else {
    add('scenes/main.tscn', mainScene(o));
    copy('scripts/main.gd', path.join(TPL, 'project', 'scripts', 'main.gd'));
  }
  copy('autoload/events.gd', path.join(TPL, 'project', 'autoload', 'events.gd'));
  add('assets/.gitkeep', '');
  add('data/.gitkeep', '');
  add('tests/README.md', TESTS_README);
  copy('tests/scenarios/smoke.gd', path.join(TPL, 'project', 'tests', 'scenarios', 'smoke.gd'));
  add('tests/replays/.gitkeep', '');
  add('tests/baselines/.gdignore', ''); // baselines are gb data, never imported or exported by Godot
  if (o.tests === 'gut') {
    const example = path.join(TPL, 'project', 'tests', 'unit', 'test_example.gd');
    // Adoption never adds an Events autoload, so the example must not assert one the project does not have.
    if (o.adopt && !o.hasEvents) add('tests/unit/test_example.gd', fs.readFileSync(example, 'utf8').replace(/\r\n/g, '\n').replace(/func test_events_autoload_exists\(\)[^\n]*\n[^\n]*\n\n\n/, ''));
    else copy('tests/unit/test_example.gd', example);
  }
  copyTree('addons/gb_harness', path.join(TPL, 'addons', 'gb_harness'));
  if (o.tests === 'gut') copyTree('addons/gut', path.join(PLUGIN, 'vendor', 'gut', 'addons', 'gut'));
  add('export_presets.cfg', exportPresets());
  add('.ai/perf-budget.json', PERF_BUDGET);
  add('.github/workflows/verify.yml', fs.readFileSync(path.join(TPL, 'repo', 'ci-verify.yml'), 'utf8').replace('{{GODOT_FULL}}', o.engineFull || o.engine));
  add('.gitignore', GITIGNORE);
  add('.gitattributes', gitattributes(o.lfs));
  add('.editorconfig', EDITORCONFIG);

  for (const f of ['gb.js', 'lint.js', 'credits.js', 'check_all.gd', 'setup_input.gd', 'project_setting.gd', 'imgdiff.gd']) copy(`tools/gb/${f}`, path.join(__dirname, f));
  add('tools/gb/.gdignore', '');
  add('tools/gb/ignore-errors.txt', IGNORE_ERRORS);

  add('AGENTS.md', fill(fs.readFileSync(path.join(TPL, 'repo', 'AGENTS.md.tmpl'), 'utf8'), o));
  add('CLAUDE.md', '@AGENTS.md\n');
  add('README.md', readme(o));
  add('STATUS.md', `# Status — ${o.name}\n\nPostęp gry wg specyfikacji (aktualizowany na każdej bramce fazy).\n\n| Spec | Faza | Stan | Grywalne? | Werdykt gracza |\n|---|---|---|---|---|\n`);

  const aiFiles = JSON.parse(fs.readFileSync(path.join(TPL, 'ai', 'files.json'), 'utf8'));
  for (const [rel, content] of Object.entries(aiFiles)) if (!rel.startsWith('_')) add(`.ai/${rel}`, content);
  for (const c of fs.readdirSync(path.join(TPL, 'ai', 'checklists'))) copy(`.ai/checklists/${c}`, path.join(TPL, 'ai', 'checklists', c));
  copy('.ai/skills/spec-writing/SKILL.md', path.join(TPL, 'ai', 'skills', 'spec-writing', 'SKILL.md'));
  add('.ai/adr/ADR-001-engine-and-setup.md', adr001(o));

  copy('.claude/settings.json', path.join(TPL, 'claude', 'settings.json'));
  copy('.claude/hooks/session-start.sh', path.join(TPL, 'claude', 'hooks', 'session-start.sh'));
  copy('.claude/hooks/guard-protected-paths.sh', path.join(TPL, 'claude', 'hooks', 'guard-protected-paths.sh'));
  copy('.claude/hooks/check-on-edit.sh', path.join(TPL, 'claude', 'hooks', 'check-on-edit.sh'));
  return files;
}

/**
 * In adopt mode the game's own files are never generated — only the methodology layer + tools.
 * Even then nothing existing is overwritten (the general rule), but skipping these keeps the
 * report honest: an adopted project does not get a placeholder main scene "KEPT" next to its own.
 */
const GAME_FILES = new Set(['project.godot', 'scenes/main.tscn', 'scripts/main.gd', 'autoload/events.gd', 'assets/.gitkeep', 'data/.gitkeep', 'export_presets.cfg']);
// Adopt installs these through `gb harness install` / `gb tests install`, which also register
// them with the engine (autoload, editor plugin) instead of copying files the project never loads.
const GAME_DIRS = ['addons/gb_harness/', 'addons/gut/'];

function scaffold(o, { runGodot = null, dryRun = false } = {}) {
  const report = [];
  for (const f of plan(o)) {
    if (o.adopt && (GAME_FILES.has(f.rel) || GAME_DIRS.some((d) => f.rel.startsWith(d)))) continue;
    const dst = path.join(o.dir, f.rel);
    if (fs.existsSync(dst)) { report.push(`KEPT    ${f.rel}`); continue; }
    report.push(`CREATED ${f.rel}`);
    if (dryRun) continue;
    fs.mkdirSync(path.dirname(dst), { recursive: true });
    if (f.src) fs.copyFileSync(f.src, dst);
    else fs.writeFileSync(dst, f.content);
  }
  if (!dryRun && runGodot) {
    const r = runGodot(['--headless', '--path', o.dir, '--script', path.join(o.dir, 'tools', 'gb', 'setup_input.gd')]);
    const m = /GB_INPUT_DONE added=(\d+) err=(\d+)/.exec(r);
    report.push(m ? `INPUT   ${m[1]} default action(s) added via Godot (existing actions untouched)` : 'FAIL    input actions: setup_input.gd did not report — run it manually');
  }
  return report;
}

function parseScaffoldArgs(argv) {
  const o = { dir: process.cwd(), name: null, dim: '2d', renderer: null, pixelArt: false, width: null, height: null, tests: 'gut', lfs: false, engine: null, adopt: false, dryRun: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const v = () => argv[++i];
    if (a === '--dir') o.dir = path.resolve(v());
    else if (a === '--name') o.name = v();
    else if (a === '--dim') { o.dim = v().toLowerCase(); o.dimGiven = true; }
    else if (a === '--renderer') o.renderer = v();
    else if (a === '--pixel-art') o.pixelArt = true;
    else if (a === '--width') o.width = Number(v());
    else if (a === '--height') o.height = Number(v());
    else if (a === '--tests') o.tests = v();
    else if (a === '--lfs') o.lfs = true;
    else if (a === '--engine') o.engine = v();
    else if (a === '--adopt') o.adopt = true;
    else if (a === '--dry-run') o.dryRun = true;
    else if (a === '--template') o.template = v();
    else throw new Error(`scaffold: unknown option ${a}`);
  }
  if (o.template) {
    const f = path.join(TPL, 'games', o.template, 'template.json');
    if (!fs.existsSync(f)) throw new Error(`scaffold: unknown template "${o.template}" (have: ${listTemplates().join(', ') || 'none'})`);
    o.templateInfo = JSON.parse(fs.readFileSync(f, 'utf8'));
    o.dim = o.templateInfo.dim;
    if (!o.width && o.templateInfo.viewport) [o.width, o.height] = o.templateInfo.viewport;
  }
  if (!['2d', '3d'].includes(o.dim)) throw new Error('scaffold: --dim must be 2d or 3d');
  const existing = path.join(o.dir, 'project.godot');
  if (o.adopt && fs.existsSync(existing)) Object.assign(o, existingSettings(fs.readFileSync(existing, 'utf8')));
  o.renderer = o.renderer || (o.dim === '3d' ? 'forward_plus' : 'gl_compatibility');
  if (!RENDERERS[o.renderer]) throw new Error(`scaffold: --renderer must be one of ${Object.keys(RENDERERS).join(', ')}`);
  if (!['gut', 'gdunit4', 'none'].includes(o.tests)) throw new Error('scaffold: --tests must be gut, gdunit4 or none');
  o.width = o.width || (o.pixelArt ? 320 : 1280);
  o.height = o.height || (o.pixelArt ? 180 : 720);
  o.name = o.name || path.basename(o.dir);
  return o;
}

/**
 * Adopt mode documents the project as it IS: renderer, base resolution, pixel-art filter and the Events
 * autoload are read from its project.godot, with Godot's own defaults where a key is absent — never the
 * new-project defaults (an adopted game without a [rendering] section runs Forward+ at 1152×648).
 */
function existingSettings(text) {
  const get = (key) => {
    const m = new RegExp(`^${key.replace(/[/.]/g, '\\$&')}=(.+)$`, 'm').exec(text);
    return m ? m[1].trim().replace(/^"|"$/g, '') : null;
  };
  const renderer = get('renderer/rendering_method');
  return {
    renderer: renderer && RENDERERS[renderer] ? renderer : 'forward_plus',
    width: Number(get('window/size/viewport_width')) || 1152,
    height: Number(get('window/size/viewport_height')) || 648,
    pixelArt: get('textures/canvas_textures/default_texture_filter') === '0',
    hasEvents: /^Events=/m.test(text),
  };
}

function listTemplates() {
  try {
    return fs.readdirSync(path.join(TPL, 'games')).filter((d) => fs.existsSync(path.join(TPL, 'games', d, 'template.json')));
  } catch {
    return [];
  }
}

module.exports = { listTemplates, scaffold, parseScaffoldArgs, projectGodot, mainScene, plan, exportPresets, existingSettings, RENDERERS };
