extends GbScenario
## Smoke scenario generated by game-builder: the main scene runs for two seconds with every
## project input action pressed once, and nothing errors. Replace or extend it with real
## gameplay scenarios (see addons/gb_harness/scenario.gd for the API).


func run() -> void:
	await wait(0.5)
	for action: String in harness().project_actions():
		await tap(action)
	await wait(1.0)
	expect(get_tree().current_scene != null, "main scene is still loaded")
